---
- name: Enable log reciving
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^#module\(load="imudp"\)', line: 'module(load="imudp")' }
    - { regexp: '^#input\(type="imudp" port="514"\)$', line: 'input(type="imudp" port="514")' }

- name: Add custom logging
  ansible.builtin.copy:
    src: "files/{{ inventory_hostname }}/rsyslog/myconf.conf"
    dest: "/etc/rsyslog.d/"
  notify: restart rsyslog

