---
- hosts: controller
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "files/managedump.sh"
        dest: "~/"
        mode: "0755"
    - name: Add custom logging
      ansible.builtin.copy:
        src: "files/dump.conf"
        dest: "/etc/rsyslog.d/dump.conf"
      notify: restart rsyslog
  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
