#Copiare script dentro la folder /usr/bin
- name: copy scripts
  ansible.builtin.copy:
    src: "files/{{ item }}.sh"
    dest: "/usr/bin/"
    mode: "766"
# owner: "root"
#    group: "root"
  with_items:
    - createuser
    - monitor

# Copiare unit dentro systemd folder ed abilitarla

- name: copy unit
  ansible.builtin.copy:
    src: "files/createuser.service"
    dest: "/etc/systemd/system/"
    mode: "755"

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: createuser

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: createuser
    enabled: yes

# Cron per schedulare jobs

- name: schedule backup
  ansible.builtin.cron:
    name: "Monitor"
    user: root
    minute: "*/5"
    job: "/usr/bin/monitor.sh"

