---
- hosts: all
  become: true
  roles:
    - network
    - ssh
  tasks:
    - name: Install utils
      apt:
        name:
          - vim
          - nano
          - tcpdump
        state: latest
        update_cache: yes
        cache_valid_time: 3600
# controller
- hosts: router
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "managedump.sh"
        dest: "~/"
        mode: '0755'
  roles:
    - rsyslog
    - dnsmasq
    - snmp-client
# agent
- hosts: agent1,agent2
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/"
        mode: '0755'
      with_items:
        - "createdump.sh"
        - "deletedump.sh"
  roles:
    - snmp-server
    - rsyslog
