---
- hosts: all
  become: true
  roles: 
    - network
  tasks:
    - name: Install utils
      apt:
        name:
          - vim
          - tcpdump
        state: latest
        update_cache: yes
        cache_valid_time: 3600

# MANAGER
- hosts: router
  become: true
  roles:
    - dnsmasq
    - routing
#    - ldap-server
#    - rsyslog
#    - snmp-client

#  Workstations
- hosts: client
  become: true
#  vars:
#    - ldap_server: ""
  roles:
#    - ldap-client
#    - snmp-server

- hosts: server
  become: true
#  vars:
#    - ldap_server: ""
  roles:
#    - ldap-client


#- name: Import manager playbook
#  ansible.builtin.import_playbook: "manager.yml"
#- name: Import workstation playbook
#  ansible.builtin.import_playbook: "workstation.yml"

