---
- hosts: all
  become: true
  roles: 
    - network
  tasks:
    - name: Install utils
      apt:
        name:
          - neovim
          - tcpdump
        state: latest
        update_cache: yes
        cache_valid_time: 3600

# Router
- hosts: ROU
  become: true
  roles:
    - dnsmasq
    - routing
    - ldap-server
    - rsyslog
#    - snmp-manager

  tasks:
    - name: Import router plabook
      ansible.builtin.import_playbook: "rou.yml"

#  Clients
- hosts: CL1
  become: true
  vars:
    - ldap_server: "10.30.128.1"
  roles:
    - ldap-client
    - snmp-agent
  tasks:
    - name: Import client playbook
      ansible.builtin.import_playbook: "cli.yml"

# Server
- hosts: SER
  become: true
#  vars:
#    - ldap_server: ""
  roles:
    - rsyslog
