---
- hosts: all
  become: true
  roles:
    - network
    - ssh
  tasks:
    - name: Install utils
      apt:
        name:
          - vim
          - nano
          - tcpdump
        state: latest
        update_cache: yes
        cache_valid_time: 3600
# controller
- hosts: controller
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "managedump.sh"
        dest: "~/"
        mode: "0755"
  roles:
    - rsyslog
    - dnsmasq
    - snmp-client
    - ssh
# agent
- hosts: agent1,agent2
  become: true
  roles:
    - snmp-server
    - rsyslog
    - ssh
- name: Import agent playbook
  ansible.builtin.import_playbook: "agent.yml"
- name: Import controller playbook
  ansible.builtin.import_playbook: "controller.yml"