---
- name: Configure slapd
  ansible.builtin.debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: "slapd/slapd/invalid_config", value: "false", vtype: "boolean" }
    - { question: "slapd/domain", value: "labammsis", vtype: "string" }
    - { question: "slapd/organization", value: "Unibo", vtype: "string" }
    - { question: "shared/organization", value: "Unibo", vtype: "string" }
    - { question: "slapd/move_old_database", value: "true", vtype: "boolean" }
    - { question: "slapd/purge_database", value: "true", vtype: "boolean" }
    - { question: "slapd/no_configuration", value: "false", vtype: "boolean" }
  notify: restart slapd
  register: slapd_config
- name: Set ldap password
  ansible.builtin.debconf:
    name: slapd
    question: "{{ item }}"
    value: "gennaio.marzo"
    vtype: "password"
  with_items:
    - "slapd/password1"
    - "slapd/password2"
  when: slapd_config.changed
- name: Install slapd
  ansible.builtin.apt:
    name: slapd
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: copy files ldif to server
  ansible.builtin.copy:
    src: "{{ item  }}"
    dest: "/etc/ldap/schema/"
    owner: "root"
    mode : "0644"
  with_fileglob: "files/*.ldif"

- name: Add entries to ldap directory
  ansible.builtin.shell:
    cmd: "ldapadd -x -D 'cn=admin,dc=labammsis' -w 'gennaio.marzo' -H
    ldap:/// -f /etc/ldap/schema/{{ item | basename}}"
  with_fileglob: "files/*.ldif"
   #  ignore_errors: yes                                                                                                                            
  register: command_result                                                                                                                       
  failed_when: "'FAILED' in command_result.stderr"
