---
#- name: Copy public keys
#  ansible.posix.authorized_key:
#    user: "vagrant"
#    key: "{{ lookup('file', 'ssh-config/id_rsa.pub') }}"
#    state: present

#- name: Copy private key
#  remote_user: vagrant
#  ansible.builtin.copy:
#    src: "ssh-config/id_rsa"
#    dest: "/home/vagrant/.ssh/id_rsa"
#    mode: 0600
#    owner: vagrant
#    group: vagrant

# ssh stuff for nerds
#- name: Check for directory
#  ansible.builtin.file:
#    path:  "{{ item }}"
#    mode: 0700
#    group: temp
#    owner: temp
#    state: directory
#  with_items:
#    - "/home/temp/"
#    - "/home/temp/.ssh/"
#
#- name: copy ssh config
#  ansible.builtin.copy:
#    src: "files/keys/ssh-config"
#    dest: "/home/temp/.ssh/config"
#    mode: 0600
#    owner: temp
#    group: temp
#
#- name: Add ssh key for temp user
#  ansible.builtin.copy:
#    src: "files/keys/id_rsa"
#    dest: "/home/temp/.ssh/"


